# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"

  before_all do
    # faselane中pod install的操作
    cocoapods
  end
  lane :enterprise do
    # add actions here: https://docs.fastlane.tools/actions
    gym(
    scheme:"demo1",
    export_method:"enterprise",
    output_directory:"/Users/edz/Desktop/自动打包--ok",
    output_name:"demo1_app"
    )
  end
end
