
default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"

  before_all do
    # faselane中pod install的操作
    # cocoapods
  end
  lane :release do

    gym(
     scheme:"demo1",
     workspace:"demo1.xcworkspace",
     export_method:"enterprise",
     output_directory:"/Users/edz/Desktop/自动打包--ok",
     output_name:"demo1_app"
    )
  end
end
